# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-27 12:50
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('price', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Total Price')),
                ('selling_price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Selling Price per Item')),
                ('discount_rate', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Discount Rate')),
                ('the_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Import',
                'verbose_name_plural': 'Imports',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Product Name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=b'Product/', verbose_name='photo')),
                ('description', models.CharField(blank=True, max_length=800, null=True, verbose_name='Description')),
                ('createdAt', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('displayFlag', models.BooleanField(default=True, verbose_name='Display to users in WebSite')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('invoice', models.FileField(editable=False, upload_to=b'invoices/', verbose_name='invoice')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('fk_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Location', to='Company.Location', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='SalesItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Price per Item')),
                ('fk_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SoldImport', to='Product.Imports', verbose_name='Import')),
                ('fk_sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sales', to='Product.Sales', verbose_name='Sales')),
            ],
            options={
                'verbose_name': 'Sales Item',
                'verbose_name_plural': 'Sales Items',
            },
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('the_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('fk_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Imports', to='Product.Imports', verbose_name='Imports')),
                ('fk_location_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TransferFrom', to='Company.Location', verbose_name='Transfer From')),
                ('fk_location_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TransferTo', to='Company.Location', verbose_name='Transfer To')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='fk_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='Product.ProductCategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='imports',
            name='fk_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='Product.Product', verbose_name='Product'),
        ),
        migrations.AlterUniqueTogether(
            name='salesitems',
            unique_together=set([('fk_sales', 'fk_import')]),
        ),
    ]
